// docs/lib/config-builder/engine.ts
// Deterministic config generation and import for the Config Builder.

import yaml from 'js-yaml';
import { BuilderNode, BuilderEdge, GeneratedArtifacts, SetupStep } from './types';
import { getAdapterById, ADAPTER_REGISTRY } from './registry';

const DOCKET_VERSION = '0.2.0';

export interface BuildConfigResult {
  object: Record<string, unknown>;
  yaml: string;
}

function isEmpty(value: unknown): boolean {
  return value === undefined || value === '' || value === null;
}

function renderConfigWithPlaceholders(
  config: Record<string, unknown>,
  schema: { key: string; envVar: string }[]
): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const field of schema) {
    const value = config[field.key];
    if (isEmpty(value)) {
      out[field.key] = `<${field.envVar}>`;
    } else {
      out[field.key] = value;
    }
  }
  return out;
}

/**
 * Generate the docket.yaml object and string from the canvas state.
 */
export function generateConfig(nodes: BuilderNode[], edges: BuilderEdge[]): BuildConfigResult {
  const platformNode = nodes.find((n) => getAdapterById(n.adapterId)?.category === 'platform');
  const platformAdapter = platformNode ? getAdapterById(platformNode.adapterId) : undefined;

  const server = platformNode
    ? { port: platformNode.config.port ?? 3000, host: platformNode.config.host ?? '127.0.0.1' }
    : { port: 3000, host: '127.0.0.1' };

  const categories = ['llm', 'embedder', 'store', 'blob', 'queue'] as const;
  const adapters: Record<string, { default: string; providers: Record<string, { adapter: string; config: Record<string, unknown> }> }> = {};

  for (const category of categories) {
    const adapterNodes = nodes.filter((n) => getAdapterById(n.adapterId)?.category === category);
    if (adapterNodes.length === 0) continue;

    const providers: Record<string, { adapter: string; config: Record<string, unknown> }> = {};
    for (const node of adapterNodes) {
      const adapter = getAdapterById(node.adapterId);
      if (!adapter) continue;
      providers[adapter.providerKey] = {
        adapter: adapter.adapterPackage,
        config: renderConfigWithPlaceholders(node.config, adapter.configSchema)
      };
    }

    adapters[category] = {
      default: adapterNodes[0] ? getAdapterById(adapterNodes[0].adapterId)!.providerKey : '',
      providers
    };
  }

  const object = {
    docket: {
      version: DOCKET_VERSION,
      server,
      logging: { level: 'info', format: 'pretty' },
      memory: { mode: 'flat' },
      adapters
    }
  };

  const yamlString = `# Docket configuration generated by the Config Builder
# Fill in any values marked with <PLACEHOLDER> before starting.
${yaml.dump(object, { indent: 2, lineWidth: -1, noCompatMode: true })}`;

  return { object, yaml: yamlString };
}

/**
 * Generate .env.example content.
 */
export function generateEnvExample(nodes: BuilderNode[]): string {
  const lines: string[] = ['# Docket environment variables generated by the Config Builder'];
  const seen = new Set<string>();

  for (const node of nodes) {
    const adapter = getAdapterById(node.adapterId);
    if (!adapter) continue;
    for (const field of adapter.configSchema) {
      if (seen.has(field.envVar)) continue;
      seen.add(field.envVar);
      const value = node.config[field.key];
      const rendered = isEmpty(value) ? `<${field.envVar}>` : String(value);
      lines.push(`export ${field.envVar}="${rendered}"`);
    }
  }

  return lines.join('\n');
}

/**
 * Generate install commands (npm + system prerequisites).
 */
export function generateInstallCommands(nodes: BuilderNode[]): string {
  const commands: string[] = ['npm install'];
  const seen = new Set<string>();
  const requires = new Set<string>();

  for (const node of nodes) {
    const adapter = getAdapterById(node.adapterId);
    if (!adapter) continue;
    if (adapter.installCommand && !seen.has(adapter.installCommand)) {
      commands.push(adapter.installCommand);
      seen.add(adapter.installCommand);
    }
    if (adapter.requires) {
      for (const req of adapter.requires) requires.add(req);
    }
  }

  if (requires.has('ollama')) {
    commands.push('# Make sure Ollama is installed and running: https://ollama.com');
  }
  if (requires.has('lm-studio')) {
    commands.push('# Make sure LM Studio is running with the server enabled');
  }

  return commands.join('\n');
}

/**
 * Generate ordered setup steps.
 */
export function generateSetupSteps(nodes: BuilderNode[], edges: BuilderEdge[]): SetupStep[] {
  const steps: SetupStep[] = [];
  const platformNode = nodes.find((n) => getAdapterById(n.adapterId)?.category === 'platform');
  const platformAdapter = platformNode ? getAdapterById(platformNode.adapterId) : undefined;
  const platformId = platformNode ? platformAdapter?.id : undefined;

  steps.push({
    order: 1,
    title: 'Install dependencies',
    description: 'Run the install commands in your project root.',
    command: generateInstallCommands(nodes)
  });

  steps.push({
    order: 2,
    title: 'Configure environment',
    description: 'Copy the generated values into a .env file or export them in your shell.',
    command: undefined
  });

  steps.push({
    order: 3,
    title: 'Write docket.yaml',
    description: 'Save the generated YAML as config/config.yaml in your project root.',
    command: undefined
  });

  const storeNode = nodes.find((n) => getAdapterById(n.adapterId)?.category === 'store');
  if (storeNode) {
    steps.push({
      order: 4,
      title: 'Run migrations',
      description: 'Initialize the store schema.',
      command: 'npm run migrate'
    });
  }

  let startCommand = 'npm start';
  if (platformId === 'control') startCommand = 'npm run start:control';
  if (platformId === 'data') startCommand = 'npm run start:data';
  if (platformId === 'standalone') startCommand = 'node src/platform/standalone/bin.js';
  if (platformId === 'serverless-aws-lambda') startCommand = '# Deploy to AWS Lambda (see serverless docs)';
  if (platformId === 'serverless-cloudflare-workers') startCommand = 'npx wrangler deploy';

  steps.push({
    order: 5,
    title: 'Start Docket',
    description: 'Launch the platform.',
    command: startCommand
  });

  steps.push({
    order: 6,
    title: 'Health check',
    description: 'Verify the system is running.',
    command: 'npm run doctor'
  });

  return steps.sort((a, b) => a.order - b.order);
}

/**
 * Generate all artifacts from the canvas state.
 */
export function generateArtifacts(nodes: BuilderNode[], edges: BuilderEdge[]): GeneratedArtifacts {
  return {
    configYaml: generateConfig(nodes, edges).yaml,
    envExample: generateEnvExample(nodes),
    installCommands: generateInstallCommands(nodes),
    setupSteps: generateSetupSteps(nodes, edges)
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Import existing docket.yaml
// ─────────────────────────────────────────────────────────────────────────────

export interface ParsedCanvas {
  nodes: BuilderNode[];
  edges: BuilderEdge[];
}


function findRegistryEntry(category: string, providerKey: string, adapterPackage: string): typeof ADAPTER_REGISTRY[number] | undefined {
  return ADAPTER_REGISTRY.find(
    (a) => a.category === category && a.providerKey === providerKey
  );
}

function gridPosition(index: number, category: string): { x: number; y: number } {
  const categoryOrder = ['platform', 'llm', 'embedder', 'store', 'blob', 'queue'];
  const col = categoryOrder.indexOf(category);
  const row = index;
  return { x: col * 280 + 40, y: row * 160 + 40 };
}

export function parseConfig(yamlString: string): ParsedCanvas {
  const parsed = yaml.load(yamlString) as Record<string, any> | null;
  if (!parsed || !parsed.docket) {
    return { nodes: [], edges: [] };
  }

  const docket = parsed.docket;
  const nodes: BuilderNode[] = [];
  const edges: BuilderEdge[] = [];

  // Add a default platform node; config does not encode platform mode.
  nodes.push({
    id: 'platform-unified',
    adapterId: 'unified',
    config: {
      port: docket.server?.port ?? 3000,
      host: docket.server?.host ?? '127.0.0.1'
    },
    position: gridPosition(0, 'platform')
  });

  const categories = ['llm', 'embedder', 'store', 'blob', 'queue'] as const;
  for (const category of categories) {
    const categoryConfig = docket.adapters?.[category];
    if (!categoryConfig || !categoryConfig.providers) continue;

    let index = 0;
    for (const [providerKey, provider] of Object.entries(categoryConfig.providers as Record<string, any>)) {
      const entry = findRegistryEntry(category, providerKey, provider.adapter);
      if (!entry) continue;

      const config: Record<string, unknown> = { ...(provider.config || {}) };
      // Normalize placeholder strings back to empty values for the inspector.
      for (const field of entry.configSchema) {
        const value = config[field.key];
        if (typeof value === 'string' && value.startsWith('<') && value.endsWith('>')) {
          config[field.key] = '';
        }
      }

      const nodeId = `${category}-${providerKey}-${index}`;
      nodes.push({
        id: nodeId,
        adapterId: entry.id,
        config,
        position: gridPosition(index, category)
      });

      edges.push({
        id: `edge-platform-${nodeId}`,
        source: 'platform-unified',
        target: nodeId,
        sourcePort: `to-${category}`,
        targetPort: 'from-platform'
      });

      index++;
    }
  }

  return { nodes, edges };
}

export function downloadFile(filename: string, content: string, type = 'text/plain'): void {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function copyToClipboard(text: string): Promise<void> {
  return navigator.clipboard.writeText(text);
}
